all:
	@echo Building challenge
	@gcc -m32 -g -no-pie -fno-stack-protector -O0 challenge.c -o challenge 2>/dev/null
	@gcc -g -no-pie -fno-stack-protector -O0 challenge.c -o challenge64 2>/dev/null
	@echo Done. Good Luck!